name: movies_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0-152.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cached_network_image: ^3.3.0
  cupertino_icons: ^1.0.6
  dartz: ^0.10.1
  data_connection_checker:
    git:
      url: https://github.com/chornthorn/data_connection_checker.git
      ref: master
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  get_it: ^7.6.4
  http: ^1.1.2
  intl: ^0.18.1
  rxdart: ^0.27.7
  shimmer: ^3.0.0
  sqflite_sqlcipher: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  flutter_native_splash: ^2.3.9
    #  flutter_launcher_icons: ^0.13.1
  flutter_launcher_icons: "^0.13.1"

flutter_native_splash:
  color: "#FFFFFF"
  color_dark: "#272727"
  image: assets/images/logo.png
  image_dark: assets/images/logo.png

  android_12:
    color: "#FFFFFF"
    color_dark: "#272727"
    image: assets/images/logo.png
    image_dark: assets/images/logo.png

  web: false


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/